package first.robot.mechanisms;

import static first.robot.Constants.ShootingConstants.HEADING_P;

import com.ctre.phoenix6.StatusSignal;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.swerve.SwerveDrivetrain.SwerveDriveState;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModule.SteerRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ForwardPerspectiveValue;
import first.robot.VisionMeasurementConsumer;
import first.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;
import org.wpilib.command3.Command;
import org.wpilib.command3.Mechanism;
import org.wpilib.command3.Scheduler;
import org.wpilib.driverstation.Alliance;
import org.wpilib.driverstation.MatchState;
import org.wpilib.driverstation.RobotState;
import org.wpilib.math.geometry.Pose2d;
import org.wpilib.math.geometry.Rotation2d;
import org.wpilib.math.geometry.Translation2d;
import org.wpilib.math.linalg.Matrix;
import org.wpilib.math.numbers.N1;
import org.wpilib.math.numbers.N3;
import org.wpilib.system.Notifier;
import org.wpilib.system.RobotController;
import org.wpilib.units.measure.AngularVelocity;
import org.wpilib.units.measure.Current;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Mechanism so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends Mechanism implements VisionMeasurementConsumer {

  private final TunerSwerveDrivetrain drivetrain;

  private static final double kSimLoopPeriod = 0.004; // 4 ms
  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  private final StatusSignal<AngularVelocity> yawVelocity;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   * <p>
   * This constructs the underlying hardware devices, so users should not construct
   * the devices themselves. If they need the devices, they can access them through
   * getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      SwerveModuleConstants<?, ?, ?>... modules) {
    drivetrain = new TunerSwerveDrivetrain(drivetrainConstants, modules);
    yawVelocity = drivetrain.getPigeon2().getAngularVelocityZWorld();
    if (Utils.isSimulation()) {
      startSimThread();
    }
    Scheduler.getDefault().addPeriodic(this::applyOperatorPerspective);
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   * <p>
   * This constructs the underlying hardware devices, so users should not construct
   * the devices themselves. If they need the devices, they can access them through
   * getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If
   *          unspecified or set to 0 Hz, this is 250 Hz on
   *          CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    drivetrain = new TunerSwerveDrivetrain(drivetrainConstants, odometryUpdateFrequency, modules);
    yawVelocity = drivetrain.getPigeon2().getAngularVelocityZWorld();
    if (Utils.isSimulation()) {
      startSimThread();
    }
    Scheduler.getDefault().addPeriodic(this::applyOperatorPerspective);
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   * <p>
   * This constructs the underlying hardware devices, so users should not construct
   * the devices themselves. If they need the devices, they can access them through
   * getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If
   *          unspecified or set to 0 Hz, this is 250 Hz on
   *          CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation
   *          in the form [x, y, theta]ᵀ, with units in meters
   *          and radians
   * @param visionStandardDeviation The standard deviation for vision calculation
   *          in the form [x, y, theta]ᵀ, with units in meters
   *          and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    drivetrain = new TunerSwerveDrivetrain(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    yawVelocity = drivetrain.getPigeon2().getAngularVelocityZWorld();
    if (Utils.isSimulation()) {
      startSimThread();
    }
    Scheduler.getDefault().addPeriodic(this::applyOperatorPerspective);
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(coroutine -> drivetrain.setControl(request.get())).named("Apply request: " + request.toString());
  }

  private void applyOperatorPerspective() {
    /*
     * Periodically try to apply the operator perspective.
     * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
     * This allows us to correct the perspective in case the robot code restarts mid-match.
     * Otherwise, only check and apply the operator perspective if the DS is disabled.
     * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
     */
    if (!m_hasAppliedOperatorPerspective || RobotState.isDisabled()) {
      MatchState.getAlliance().ifPresent(allianceColor -> {
        drivetrain.setOperatorPerspectiveForward(
            allianceColor == Alliance.RED ? kRedAlliancePerspectiveRotation : kBlueAlliancePerspectiveRotation);
        m_hasAppliedOperatorPerspective = true;
      });
    }
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier = new Notifier(() -> {
      final double currentTime = Utils.getCurrentTimeSeconds();
      double deltaTime = currentTime - m_lastSimTime;
      m_lastSimTime = currentTime;

      /* use the measured time delta, get battery voltage from WPILib */
      drivetrain.updateSimState(deltaTime, RobotController.getBatteryVoltage());
    });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Gets the yaw angular velocity of the drivetrain from the IMU (not from the pose estimator).
   *
   * @return current yaw angular velocity
   */
  public AngularVelocity getIMUYawVelocity() {
    return yawVelocity.refresh().getValue();
  }

  /**
   * Sets the supply current limit for all drive motors. This calls TalonFXConfigurator.apply(), so it may be a blocking
   * call. It must not be called periodically, and probably shouldn't be called when the robot is enabled.
   * 
   * @param newLimit new supply current limit to set for all drive motors
   */
  public void setDriveSupplyCurrentLimit(Current newLimit) {
    for (var module : drivetrain.getModules()) {
      var currentLimits = new CurrentLimitsConfigs();
      var motor = module.getDriveMotor();
      var configurator = motor.getConfigurator();
      configurator.refresh(currentLimits);
      currentLimits.withSupplyCurrentLimit(newLimit);
      configurator.apply(currentLimits);
    }
  }

  /**
   * Register the specified lambda to be executed whenever our SwerveDriveState function
   * is updated in our odometry thread.
   * <p>
   * It is imperative that this function is cheap, as it will be executed along with
   * the odometry call, and if this takes a long time, it may negatively impact the
   * odometry of this stack.
   * <p>
   * This can also be used for logging data if the function performs logging instead of telemetry.
   * Additionally, the SwerveDriveState object can be cloned and stored for later processing.
   *
   * @param telemetryFunction Function to call for telemetry or logging
   */
  public void registerTelemetry(Consumer<SwerveDriveState> telemetryFunction) {
    drivetrain.registerTelemetry(telemetryFunction);
  }

  /**
   * Gets the current state of the swerve drivetrain.
   * This includes information such as the pose estimate,
   * module states, and chassis velocity.
   *
   * @return Current state of the drivetrain
   */
  public SwerveDriveState getState() {
    return drivetrain.getState();
  }

  public Command pointAtTarget(
      Function<Translation2d, Translation2d> targetTranslationSelector,
      Rotation2d offsetAngle) {
    final SwerveRequest.FieldCentricFacingAngle swerveRequestFacing = new SwerveRequest.FieldCentricFacingAngle()
        .withForwardPerspective(ForwardPerspectiveValue.BlueAlliance)
        .withHeadingPID(HEADING_P, 0, 0)
        .withDriveRequestType(DriveRequestType.Velocity)
        .withSteerRequestType(SteerRequestType.MotionMagicExpo)
        .withVelocityX(0.0)
        .withVelocityY(0.0);
    return run(coroutine -> {
      var robotPose = getState().Pose;
      var targetTranslation2 = targetTranslationSelector.apply(robotPose.getTranslation());
      var headingToTarget = targetTranslation2.minus(robotPose.getTranslation()).getAngle().minus(offsetAngle);
      drivetrain.setControl(swerveRequestFacing.withTargetDirection(headingToTarget));
    }).named("Point at target");
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the
   * odometry pose estimate while still accounting for measurement noise.
   * <p>
   * This method can be called as infrequently as you want.
   * <p>
   * To promote stability of the pose estimate and make it robust to bad vision
   * data, we recommend only adding vision measurements that are already within
   * one meter or so of the current pose estimate.
   * <p>
   * Note that the vision measurement standard deviations passed into this method
   * will continue to apply to future measurements until a subsequent call to
   * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the
   *          vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in
   *          seconds. Note that you must use a timestamp with an
   *          epoch since system startup (i.e., the epoch of this
   *          timestamp is the same epoch as
   *          {@link Utils#getCurrentTimeSeconds}).
   *          This means that you should use
   *          {@link Utils#getCurrentTimeSeconds}
   *          as your time source or sync the epochs.
   * @param visionMeasurementStdDevs Standard deviations of the vision pose
   *          measurement (x position
   *          in meters, y position in meters, and heading
   *          in radians). Increase these numbers to trust
   *          the vision pose measurement less.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    drivetrain.addVisionMeasurement(visionRobotPoseMeters, timestampSeconds, visionMeasurementStdDevs);
  }

  /**
   * Resets the pose of the robot. The pose should be from the
   * {@link SwerveRequest.ForwardPerspectiveValue#BlueAlliance} perspective.
   *
   * @param pose Pose to make the current pose
   */
  public void resetPose(Pose2d pose) {
    drivetrain.resetPose(pose);
  }

}
